name: Test
# comment
on:
  push:
    branches: [ "main" ]
  pull_request_target:
    types:
      - closed
  workflow_dispatch:

jobs:
  build:
    if: |
      !(github.event_name == 'pull_request_target' && 
      github.event.pull_request.merged == false)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Say hello
      run: echo ${{github.ref}}
