name: Test
# comment
on:
  push:
    branches: [ "main" ]
  pull_request:
    types:
      - closed
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Say hello
      run: echo ${{github.ref_name}}
