name: Test
# comment
on:
  push:
    branches: [ "main" ]
  pull_request_target:
    types:
      - closed
    branches: 'main'
  workflow_dispatch:

jobs:
  build:
    if: |
        !((github.event.pull_request.merged == false) && 
        ((github.base_ref == 'master') || 
        (github.base_ref == 'release/*'))) || 
        (github.event_name == 'push')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Say hello
      run: echo ${{github.ref}}
